development:
  -
    :host: '0.0.0.0'
    :http_port: 15000
    :pb_port: 15001

test:
  -
    :host: '0.0.0.0'
    :http_port: 15000
    :pb_port: 15001
    
production:
  -
    :host: '0.0.0.0'
    :http_port: 15000
    :pb_port: 15001
